# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IUvzdg5pHTmsDFXZI_IHjF6OGP61QWB
"""

import numpy as np
import matplotlib.pyplot as plt

# Time: one week = 168 hours
t = np.linspace(0, 168, 1000)

# Global weekly cycle
weekly = np.sin(2 * np.pi * t / 168)

# Daily cycle
daily = 0.6 * np.sin(2 * np.pi * t / 24)

# 12-hour harmonic
half_daily = 0.5 * np.sin(2 * np.pi * t / 12)

# Plot
plt.plot(t, weekly, label="Weekly cycle (168 h)")
plt.plot(t, daily, label="Daily cycle (24 h)")
plt.plot(t, half_daily, label="12 h harmonic")

plt.xlabel("Time (hours)")
plt.ylabel("Amplitude")
plt.title("NeAR: Multi-scale Periodic Cycles")

plt.legend()
plt.grid(alpha=0.25)

plt.show()