# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IUvzdg5pHTmsDFXZI_IHjF6OGP61QWB
"""

import numpy as np
import matplotlib.pyplot as plt

t = np.linspace(0, 168, 1000)

weekly = np.sin(2 * np.pi * t / 168)

plt.plot(t, weekly)

plt.xlabel("Time (hours)")
plt.ylabel("Amplitude")
plt.title("Weekly Cycle")

plt.show()