# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IUvzdg5pHTmsDFXZI_IHjF6OGP61QWB
"""

resonance = weekly + daily + half_daily + eight_hour

import numpy as np
import matplotlib.pyplot as plt

# Time: one week = 168 hours
t = np.linspace(0, 168, 1000)

# Global weekly cycle
weekly = np.sin(2 * np.pi * t / 168)

# Local daily cycle
daily = 0.6 * np.sin(2 * np.pi * t / 24)

# 12-hour harmonic
half_daily = 0.5 * np.sin(2 * np.pi * t / 12)

# 8-hour harmonic
eight_hour = 0.4 * np.sin(2 * np.pi * t / 8)

# Combine all cycles
resonance = weekly + daily + half_daily + eight_hour

# Plot the combined resonance
plt.plot(t, resonance, label="Combined resonance")

plt.xlabel("Time (hours)")
plt.ylabel("Amplitude")
plt.title("NeAR: Multi-scale Periodic Resonance")

plt.legend()
plt.grid(alpha=0.25)

plt.show()